Document: nxsite
Title: Debian nxsite Manual
Author: <insert document author here>
Abstract: This manual describes what nxsite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nxsite/nxsite.sgml.gz

Format: postscript
Files: /usr/share/doc/nxsite/nxsite.ps.gz

Format: text
Files: /usr/share/doc/nxsite/nxsite.text.gz

Format: HTML
Index: /usr/share/doc/nxsite/html/index.html
Files: /usr/share/doc/nxsite/html/*.html
